[package]
name = "believmr"
version = "0.1.0"
authors = ["Strexicious <strexicious@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.94", features = ["derive"] }
bincode = "1.1.4"
